name: CRYO2ICE_env
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.13
  - anyio=4.0.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astroid=2.15.8
  - asttokens=2.4.1
  - async-lru=2.0.4
  - atomicwrites=1.4.1
  - attrs=23.1.0
  - autopep8=2.0.4
  - babel=2.13.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bcrypt=4.0.1
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - black=23.10.1
  - bleach=6.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cartopy=0.20.0
  - certifi=2023.11.17
  - cffi=1.16.0
  - cftime=1.6.2
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.1.4
  - cookiecutter=2.4.0
  - cryptography=41.0.5
  - curl=8.1.2
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20230430
  - dill=0.3.7
  - docstring-to-markdown=0.13
  - docutils=0.20.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - flake8=6.0.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - geos=3.9.1
  - gettext=0.21.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - gst-plugins-base=1.22.6
  - gstreamer=1.22.6
  - h5py=3.7.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - inflection=0.5.1
  - intel-openmp=2023.2.0
  - intervaltree=3.1.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - ipython_genutils=0.2.0
  - isoduration=20.11.0
  - isort=5.12.0
  - jaraco.classes=3.3.0
  - jedi=0.18.2
  - jellyfish=1.0.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.2
  - jupyter-lsp=2.2.0
  - jupyter_client=8.5.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.9.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.7
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - keyring=24.2.0
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lazy-object-proxy=1.9.0
  - lcms2=2.12
  - lerc=4.0.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.1.2
  - libdeflate=1.19
  - libffi=3.4.2
  - libglib=2.78.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libogg=1.3.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libsqlite=3.43.2
  - libssh2=1.11.0
  - libtiff=4.2.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzip=1.10.1
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mistune=3.0.1
  - mkl=2023.2.0
  - more-itertools=10.1.0
  - msys2-conda-epoch=20160418
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbconvert-core=7.10.0
  - nbconvert-pandoc=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.8
  - netcdf4=1.6.0
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numpy=1.20.3
  - numpydoc=1.5.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=3.2.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=1.3.4
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - paramiko=3.3.1
  - parso=0.8.3
  - pathspec=0.11.2
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - pluggy=1.3.0
  - ply=3.11
  - proj=8.0.1
  - prometheus_client=0.18.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - proplot=0.9.5
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.0.1
  - pygments=2.16.1
  - pylint=2.17.7
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyparsing=3.1.1
  - pyproj=3.3.0
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqtwebengine=5.15.9
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.1
  - python-json-logger=2.0.7
  - python-lsp-black=1.3.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.7.4
  - python-lsp-server-base=1.7.4
  - python-slugify=8.0.1
  - python_abi=3.9
  - pytoolconfig=1.2.5
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pywin32=306
  - pywin32-ctypes=0.2.2
  - pywinpty=2.0.12
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qdarkstyle=3.1
  - qstylizer=0.2.2
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - qtawesome=1.2.3
  - qtconsole=5.4.4
  - qtconsole-base=5.4.4
  - qtpy=2.4.1
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.6.0
  - rope=1.10.0
  - rpds-py=0.10.6
  - rtree=1.1.0
  - scikit-learn=1.2.2
  - scipy=1.7.1
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - send2trash=1.8.2
  - setuptools=59.8.0
  - shapely=1.7.1
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.2.6
  - sphinxcontrib-applehelp=1.0.7
  - sphinxcontrib-devhelp=1.0.5
  - sphinxcontrib-htmlhelp=2.0.4
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.6
  - sphinxcontrib-serializinghtml=1.1.9
  - spyder=5.4.5
  - spyder-kernels=2.4.4
  - sqlite=3.43.2
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - tbb=2021.10.0
  - terminado=0.15.0
  - text-unidecode=1.3
  - textdistance=4.5.0
  - threadpoolctl=3.2.0
  - three-merge=0.1.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.1
  - tornado=6.3.3
  - traitlets=5.13.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - ujson=5.8.0
  - uri-template=1.3.0
  - urllib3=2.0.7
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - watchdog=3.0.0
  - wcwidth=0.2.9
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.4
  - whatthepatch=1.0.5
  - wheel=0.41.3
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.15.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yapf=0.40.1
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - astropy==6.0.0
    - astropy-iers-data==0.2023.12.4.0.30.20
    - blosc2==2.3.2
    - msgpack==1.0.7
    - ndindex==1.7
    - numexpr==2.8.7
    - py-cpuinfo==9.0.0
    - pyerfa==2.0.1.1
    - tables==3.9.2
    - your-package==1.0
